### ISSUE TITLE
It's not working on Mac

### ISSUE THREAD

**Issue by ksidibe** [paulvl/backup#11]
Good initiative. I have properly installed the package via composer, published and edited the config file. But I ran `php artisan backup:mysql-dump xxxxxx_dash_xxxxxx`
I got the following output 

> mysqldump: [Warning] Using a password on the command line interface can be insecure.
Database 'pos_dash' dumped  successfully
But the output file exists nowhere on computer.
## System Info

- OS: MacOs Sierra v 10.12.4
- PHP: 7.1.1 (cli) (built: Jan 19 2017 13:56:18)
- Laravel: 5.3.31
Any ideas?

**Comment by paulvl** [comment]
Hi @ksidibe rry for late response. I'm unable to recreate your situation because I can't test it on mac, but can you check if the "local-storage" path exists or folder is writeable, it uses Laravel's Storage to store database backups, it supposed to store in your-app-root/storage/backups
Please confirm if you were able to fix this.

**Comment by paulvl** [comment]
Closing this because @ksidibe never replied, I assume that He fixed it.
