### ISSUE TITLE
Why I can't restore my database when is called programmatically?

### ISSUE THREAD

**Issue by AshassainRosy** [paulvl/backup#13]
hola paul, escribire en español ya que mi ingles es muy pobre,
al momento de restaurar el ultimo backup que tengo aplico la siguiente linea codigo
`Artisan::call("backup:mysql-restore",["--restore-latest-backup"=>true]);`  el cual no me retorna nada y hace que mi pantalla quede toda blanca...
Quisiera saber si es problema del paquete o yo lo estoy utilizando de mala forma, estoy toda una tarde tratando de solucionarlo pero nada. Te agradeceria si respondieras

-------------------------
English translation
-------------------------
Hi paul, i'll write in spanish because my english is poor,
at the moment to restore my latest backup I use the following code:
`Artisan::call("backup:mysql-restore",["--restore-latest-backup"=>true]);`  it doesn't return nothing and my screen stays blank...
I want to know if there is package's issue or if I'm doing something wrong, I spent a lot of time trying to figure it out. I'll be glad if you can answer me

**Comment by paulvl** [comment]
Hola @AshassainRosy el problema radica en que el comando de restauración es interactivo, al ejecutarlo te pedirá confirmar si deseas restaurar la copia de seguridad, y al llamarlo programáticamente esta interactividad genera una espera indeterminada, por eso tu pantalla se queda en blanco porque está esperando la confirmación. Para hacer que funcione necesitas confirmar la restauración con la opcion --yes. El código que funciona es el siguiente:

`
\Artisan::call("backup:mysql-restore",["--restore-latest-backup" => true, '--yes' => true]);
`

-------------------------
English translation
-------------------------
Hi @AshassainRosy the problem is that the restoration command is interactive, when you execute it, you'll be prompted to confirm if you want restore your database backup, and when you call it programmatically this interactivity generates an indeterminate wait, that’s why your screen stays blank because it waiting for you to confirm this action. To make it work programmatically you need to confirm the restoration action using the --yes option. The working code is as follows:

`
\Artisan::call("backup:mysql-restore",["--restore-latest-backup" => true, '--yes' => true]);
`

**Comment by AshassainRosy** [comment]
Muchisimas gracias paul
